<?php

namespace Study\AspirinaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DcfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DcfRepository extends EntityRepository
{
}
