jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Study\AspirinaBundle\Entity\User: sha512

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database:
            entity: { class: AspirinaBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # URL anonymous
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }      
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }    
        
        # URL protected
        - { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/site, roles: ROLE_ADMIN}
        
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
