aspirina_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AspirinaBundle:Default:index }

AspirinaBundle_site:
    resource: "@AspirinaBundle/Resources/config/routing/site.yml"
    prefix:   /site