AspirinaBundle:
    resource: "@AspirinaBundle/Controller"
    prefix:  /
    type: annotation

AspirinaBundle_site:
    resource: "@AspirinaBundle/Resources/config/routing/site.yml"
    prefix:   /site