parameters:
#    aspirina.example.class: Study\AspirinaBundle\Example

services:
#    aspirina.example:
#        class: %aspirina.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
